/*
 *
 * An example showing how to write a bitmap file to the sdcard
 *
 * NOTE: This image must be either a bitmap in the 565, RGB or RGBA formats or a
 * image in the pi format. (These are generated by the Gimp plugin)
 * 
 * RGBA will probably be fased out of the library in favor of a pi image with
 * transparency. If you think you would use this format with the pi or think it 
 * would be helpful to keep for any reason shoot me an email at tim@thepiwatch.com
 *
 */

#include <SD.h>
#include <SPI.h>

#include <EEPROM.h>
#include <PiWatch.h>

PiWatch watch;

void setup() {

  // This does all of the setup for the watch hardware
  watch.init();
  
  // Fill the whole screen with white
  watch.setColor(VGA_WHITE);
  watch.fillRect(0,0,219,219);
  
  // The brightness starts out at zero so this line is what turns the 
  // backlight on so we can actually see what's on the screen. Doing 
  // this after the image has been printed to the screen gives the 
  // effect of the image 'fading' in
  watch.rampBrightness(UP);
  
}

void loop() {

    


}
